SchoolMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('teacher.urls')),
    path('',include('student.urls')),
    path('',include('faculty.urls')),
    path('',include('session.urls')),
    path('',include('attendance.urls')),
    path('',include('marks.urls')),
    path('',include('notice.urls')),
    path('',include('notes.urls')),
    path('',include('routine.urls')),
    path('',include('assignment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marks/urls.py
from django.urls import path
from .views import (
    MarksInp,
    ProvideMarks,
    Add_Marks,
    ShowMarks,
    MarksUpdate,
    get_package_detail,
    get_marks,
    deletemarks,
    MarksCreate,
    MarksOfStudent,
	)

app_name='marks'
urlpatterns = [
    path('marks-input/',MarksInp.as_view(),name='marks-input'),
    path('provide-marks/',ProvideMarks.as_view(),name='provide-marks'),
    path('add-marks',Add_Marks.as_view(),name='add-marks'),
    path('show-marks',ShowMarks.as_view(),name='show-marks'),
    path('marks-update/<int:pk>/',MarksUpdate.as_view(),name='marks-update'),
    path('marks-create/',MarksCreate.as_view(),name='marks-create'),
    path('delete-marks/<int:id>/',deletemarks,name='delete-marks'),
    path('marks-student/',MarksOfStudent.as_view(),name='marks-student'),

    path('package-detail/', get_package_detail, name='package-request'),
    path('get-marks/',get_marks,name='marks-request'),
    

]

notes/urls.py
from django.urls import path

from .views import (
    NoteList,
    NoteDownload,
    NoteListDetail,
    NoteCreate,
    NoteUpdate,
    NoteDelete,
    StudentNotes,
	)

app_name='notes'
urlpatterns = [
    path('note-list/',NoteList.as_view(),name='note-list'),
    path('note-download/<int:pk>/',NoteDownload.as_view(),name='note-download'),
    path('note-detail/<int:pk>/',NoteListDetail.as_view(),name='note-detail'),
    path('note-create/',NoteCreate.as_view(),name='note-create'),
    path('note-update/<int:pk>/',NoteUpdate.as_view(),name='note-update'),
    path('note-delete/<int:pk>/',NoteDelete.as_view(),name='note-delete'),
    path('student-note/',StudentNotes.as_view(),name='student-note'),
]

notice/urls.py
from django.urls import path
from .views import (
    notice,
    StudentNotice,
	)

app_name='notice'
urlpatterns = [
    path('notice/',notice,name='notice'),
    path('student-notice-list/',StudentNotice.as_view(),name='student-notice'),
]

session/urls.py
from django.urls import path
from .views import (
    LoginView,
    logout
	)

app_name='session'
urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',logout,name='logout')
]

student/urls.py
from django.urls import path
from .views import (
    StudentDashboard,
    StudentProfile,
    StudentProfileUpdate,
	)

app_name='student'
urlpatterns = [
    path('student-dashboard/',StudentDashboard.as_view(),name='student-dashboard'),
    path('student-profile/',StudentProfile.as_view(),name='student-profile'),
    path('student-update/<int:pk>/',StudentProfileUpdate.as_view(),name='student-update'),
]

templates/partials/student-partials/footer.html
<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                2015 - 2019 &copy; UBold theme by <a href="">Coderthemes</a> 
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-sm-block">
                    <a href="javascript:void(0);">About Us</a>
                    <a href="javascript:void(0);">Help</a>
                    <a href="javascript:void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

templates/partials/student-partials/left-sidebar.html
{% load static}
<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">

  <div class="slimscroll-menu">

    <!--- Sidemenu -->
    <div id="sidebar-menu">

      <ul class="metismenu" id="side-menu">
          <li class="menu-title">Navigation</li>

          <li>
              <a href="{% url 'student:student-profile' %}">
                  <i class="pe-7s-user"></i>
                  <span class="badge badge-success badge-pill float-right"></span>
                  <span> User PROFILE </span>
              </a>
          </li>
          <li>
              <a href="{% url 'attendance:student-attendance' %}">
                  <i class="pe-7s-date"></i>
                  <span class="badge badge-success badge-pill float-right"></span>
                  <span > ATTENDENCE </span>
              </a>
          </li>

          <li>
              <a href="{% url 'notice:student-notice' %}">
                  <i class="pe-7s-news-paper"></i>
                  <span class="badge badge-success badge-pill float-right"></span>
                  <span> NOTICE </span>
              </a>
          </li>
          <li>
              <a href="{% url 'notes:student-note' %}">
                  <i class="pe-7s-file"></i>
                  <span class="badge badge-success badge-pill float-right"></span>
                  <span> NOTES </span>
              </a>
          </li>
          <li>
              <a href="{% url 'marks:marks-student' %}">
                  <i class="pe-7s-note2"></i>
                  <span class="badge badge-success badge-pill float-right"></span>
                  <span> MARKS </span>
              </a>
          </li>
          <li>
              <a href="{% url 'assignment:student-assignment' %}">
                  <i class="pe-7s-note2"></i>
                  <span class="badge badge-success badge-pill float-right"></span>
                  <span> ASSIGNMENT </span>
              </a>
          </li>


      </ul>

    </div>
    <!-- End Sidebar -->

    <div class="clearfix"></div>

  </div>
  <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->

templates/partials/student-partials/right-sidebar.html
<!-- Right Sidebar -->
<div class="right-bar">
    <div class="rightbar-title">
        <a href="javascript:void(0);" class="right-bar-toggle float-right">
            <i class="dripicons-cross noti-icon"></i>
        </a>
        <h5 class="m-0 text-white">Settings</h5>
    </div>
    <div class="slimscroll-menu">
        <!-- User box -->
        <div class="user-box">
            <div class="user-img">
                <img src="assets/images/users/user-1.jpg" alt="user-img" title="Mat Helme" class="rounded-circle img-fluid">
                <a href="javascript:void(0);" class="user-edit"><i class="mdi mdi-pencil"></i></a>
            </div>
            
            <h5><a href="javascript: void(0);">Geneva Kennedy</a> </h5>
            <p class="text-muted mb-0"><small>Admin Head</small></p>
        </div>

        <!-- Settings -->
        <hr class="mt-0" />
        <h5 class="pl-3">Basic Settings</h5>
        <hr class="mb-0" />

        <div class="p-3">
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox1" type="checkbox" checked>
                <label for="Rcheckbox1">
                    Notifications
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox2" type="checkbox" checked>
                <label for="Rcheckbox2">
                    API Access
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox3" type="checkbox">
                <label for="Rcheckbox3">
                    Auto Updates
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox4" type="checkbox" checked>
                <label for="Rcheckbox4">
                    Online Status
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-0">
                <input id="Rcheckbox5" type="checkbox" checked>
                <label for="Rcheckbox5">
                    Auto Payout
                </label>
            </div>
        </div>

        <!-- Timeline -->
        <hr class="mt-0" />
        <h5 class="pl-3 pr-3">Messages <span class="float-right badge badge-pill badge-danger">25</span></h5>
        <hr class="mb-0" />
        <div class="p-3">
            <div class="inbox-widget">
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-2.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Tomaslau</a></p>
                    <p class="inbox-item-text">I've finished it! See you so...</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-3.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Stillnotdavid</a></p>
                    <p class="inbox-item-text">This theme is awesome!</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-4.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Kurafire</a></p>
                    <p class="inbox-item-text">Nice to meet you</p>
                </div>

                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-5.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Shahedk</a></p>
                    <p class="inbox-item-text">Hey! there I'm available...</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="assets/images/users/user-6.jpg" class="rounded-circle" alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Adhamdannaway</a></p>
                    <p class="inbox-item-text">This theme is awesome!</p>
                </div>
            </div> <!-- end inbox-widget -->
        </div> <!-- end .p-3-->

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>

templates/partials/student-partials/topbar.html
{% load static %}
<!-- Topbar Start -->
<div class="navbar-custom">
    <ul class="list-unstyled topnav-menu float-right mb-0">
        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle  waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <i class=" "></i>
                <span>Welcome MR. {{request.session.user_name}} </span>
            </a>
            
        </li>

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="" href="{% url 'session:logout' %}" role="" aria-haspopup="false" aria-expanded="false">
                <span class="">
                    Logout
                </span>
            </a>
        </li>


    </ul>

    <!-- LOGO -->
    <div class="logo-box">
        <a href="#" class="logo text-center">
            <span class="logo-lg">
                <img src="{% static 'assets/images/logo-dark.png' %}" alt="" height="18">
                <!-- <span class="logo-lg-text-light">UBold</span> -->
            </span>
            <span class="logo-sm">
                <!-- <span class="logo-sm-text-dark">U</span> -->
                <img src="{% static 'assets/images/logo-sm.png' %}" alt="" height="24">
            </span>
        </a>
    </div>

    <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
        <li>
            <button class="button-menu-mobile waves-effect waves-light">
                <i class="fe-menu"></i>
            </button>
        </li>

    </ul>
</div>
<!-- end Topbar -->