SchoolMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('teacher.urls')),
    path('',include('student.urls')),
    path('',include('faculty.urls')),
    path('',include('session.urls')),
    path('',include('attendance.urls')),
    path('',include('marks.urls')),
    path('',include('notice.urls')),
    path('',include('notes.urls')),
    path('',include('routine.urls')),
    path('',include('assignment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment/urls.py
from django.urls import path
from .views import (
	AssignmentList,
    AssignmentCreate,
    AssignmentUpdate,
    AssignmentDelete,
    StudentAssignmentList,
	)

app_name='assignment'
urlpatterns = [
	path('assignment-list/',AssignmentList.as_view(),name='assignment-list'),
    path('assignment-create/',AssignmentCreate.as_view(),name='assignment-create'),
    path('assignment-update/<int:pk>/',AssignmentUpdate.as_view(),name='assignment-update'),
    path('assignment-delete/<int:pk>/',AssignmentDelete.as_view(),name='assignment-delete'),
    path('student-assignment-list/',StudentAssignmentList.as_view(),name='student-assignment'),
]

marks/urls.py
from django.urls import path
from .views import (
    MarksInp,
    ProvideMarks,
    Add_Marks,
    ShowMarks,
    MarksUpdate,
    get_package_detail,
    get_marks,
    deletemarks,
    MarksCreate,
    MarksOfStudent,
	)

app_name='marks'
urlpatterns = [
    path('marks-input/',MarksInp.as_view(),name='marks-input'),
    path('provide-marks/',ProvideMarks.as_view(),name='provide-marks'),
    path('add-marks',Add_Marks.as_view(),name='add-marks'),
    path('show-marks',ShowMarks.as_view(),name='show-marks'),
    path('marks-update/<int:pk>/',MarksUpdate.as_view(),name='marks-update'),
    path('marks-create/',MarksCreate.as_view(),name='marks-create'),
    path('delete-marks/<int:id>/',deletemarks,name='delete-marks'),
    path('marks-student/',MarksOfStudent.as_view(),name='marks-student'),

    path('package-detail/', get_package_detail, name='package-request'),
    path('get-marks/',get_marks,name='marks-request'),
    

]

assignment/models.py
from django.db import models


class Assignment(models.Model):
    afname = models.CharField(max_length=100)
    asbatch = models.IntegerField()
    aname = models.CharField(max_length=200)
    asubject = models.CharField(max_length=200)
    adeadline = models.DateField(auto_now=False)
    document = models.FileField(default = None, blank=True)

    class Meta:
        db_table = "assignment"
    def __str__(self):
    	return (self.aname + " - Batch : " + str(self.abatch))

assignment/forms.py
from django import forms
from .models import Assignment

class AssignmentCreateForm(forms.ModelForm):
	afname = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter faculty Here'}
		))
	asbatch = forms.IntegerField(widget=forms.NumberInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Batch Here'}
		))
	aname = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Assignment Name Here'}
		))
	asubject = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter  Subject Name Here'}
		))
	adeadline = forms.DateField(widget=forms.DateInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Deadline Here'}
    ))
	document = forms.FileField(widget=forms.ClearableFileInput(
		attrs={'class':'form-control','placeholder':'File Here'}))
	class Meta:
		model = Assignment
		fields = ['afname','asbatch','aname','asubject','adeadline','document']


class AssignmentUpdateForm(forms.ModelForm):
	afname = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter faculty Here'}
		))
	asbatch = forms.IntegerField(widget=forms.NumberInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Batch Here'}
		))
	aname = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Assignment Name Here'}
		))
	asubject = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter  Subject Name Here'}
		))
	adeadline = forms.DateField(widget=forms.DateInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Deadline Here','id':'adeadline'}
    ))
	document = forms.FileField(widget=forms.ClearableFileInput(
		attrs={'class':'form-control','placeholder':'File Here'}))
	class Meta:
		model = Assignment
		fields = ['afname','asbatch','aname','asubject','adeadline','document']

assignment/views.py
from django.shortcuts import render,redirect,reverse
from django.views.generic import ListView
from django.views.generic import TemplateView


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormView

from .models import Assignment
from .forms import AssignmentCreateForm,AssignmentUpdateForm
from faculty.models import Faculty

class AssignmentList(ListView):

    template_name = 'assignment/assignment-list.html'

    def get(self, request, *args, **kwargs):
        assignment = Assignment.objects.all()
        return render(request, self.template_name, {'assignments':assignment})

class AssignmentCreate(CreateView):
    model=Assignment
    template_name = 'assignment/assignment-create.html'
    form_class = AssignmentCreateForm
    success_url = '/assignment-list/'

    def get_context_data(self, **kwargs):
        context = super(AssignmentCreate, self).get_context_data(**kwargs)
        # context['user'] = self.get_object()
        obj = Faculty.objects.all()
        context['faculty'] = obj
        return context

# class AssignmentCreate(FormView):
    
#     def get(self, request):
#         content={}
#         content['form'] =AssignmentCreateForm
#         return render(request, 'assignment/assignment-create.html', content)

#     def post(self, request):
#         content = {}
#         form = AssignmentCreateForm(request.POST, request.FILES or None)
#         adeadline = request.POST.get('adeadline',None)
#         # print('deadline',adeadline)
#         asbatch= request.POST.get('asbatch',None)
#         if form.is_valid():
#             print('document',form.cleaned_data['document'])
#             # print('adeadline',adeadline)
            
#             Assignment.objects.create(document=form.cleaned_data['document'],adeadline=adeadline,afname=form.cleaned_data['afname'],asbatch=asbatch,asubject=form.cleaned_data['asubject'],aname=form.cleaned_data['aname'])
#             return redirect(reverse('assignment:assignment-list'))
#         content['form'] = form
#         return render(request, 'assignment/assignment-create.html', content)

class AssignmentUpdate(UpdateView):
    model=Assignment
    template_name = 'assignment/assignment-update.html'
    form_class = AssignmentUpdateForm
    success_url = '/assignment-list/'

class AssignmentDelete(DeleteView):
    template_name = 'assignment/assignment-delete.html'
    model = Assignment
    success_url = '/assignment-list/'


class StudentAssignmentList(TemplateView):

    template_name = 'assignment/student-assignment-list.html'

    def get(self, request, *args, **kwargs):
        assignment = Assignment.objects.all()
        return render(request, self.template_name, {'assignments':assignment})

templates/assignment/assignment-create.html
    
{% extends "teacher_auth_base.html" %}
{% load static  %}
{% block extra_css %}
{% endblock %}
{% block content %}
    <!-- Start Content-->
    <!-- Start Content-->
                    <div class="container-fluid">
                        <!-- start page title -->
                            <div class="row" style="margin-top:-25px">
                                <div class="col-12">
                                    <div class="page-title-box">
                                        <div class="page-title-right">
                                            <ol class="breadcrumb m-0">
                                                <li class="breadcrumb-item"><a href="javascript: void(0);">CMS</a></li>
                                                <li class="breadcrumb-item"><a href="javascript: void(0);">Notes</a></li>
                                                <li class="breadcrumb-item active">Create Note</li>
                                            </ol>
                                        </div>
                                        <h4 class="page-title"></h4>
                                    </div>
                                </div>
                            </div>
                            <!-- end page title -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="mb-3 header-title">Create Notes</h4>
                                        <form  action="" method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="form-group mb-3">
                                                        <label name='afname' for="afname">Faculty</label>
                                                        <!-- {{form.afname}}
                                                        {{ form.errors.afname }} -->
                                                        <select name="afname" id="afname" required="True"
                                                                class="form-control">
                                                            <!-- <option selected disabled>Select Your Faculty</option> -->
                                                            {% for fac in faculty %}
                                                                <option>{{ fac }}</option>
                                                            {% endfor %}
                                                        </select>

                                                    </div>
                                                    <!-- <div class="form-group mb-3">
                                                        <label name='asbatch' for="asbatch">Batch</label>
                                                        {{form.asbatch}}
                                                        {{ form.errors.asbatch }}

                                                    </div> -->
                                                    <div class="form-group mb-3">
                                                        <label for="exampleFormControlSelect2">Batch</label>
                                                        <select class="form-control" name="asbatch" placeholder="Select batch" id="asbatch">
                                                          <option value="2068">2068</option>
                                                          <option value="2069">2069</option>
                                                          <option value="2070">2071</option>
                                                          <option value="2071">2071</option>
                                                          <option value="2072">2072</option>
                                                          <option value="2073">2073</option>
                                                          <option value="2074">2074</option>
                                                          <option value="2075">2075</option>
                                                        </select>
                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label name='aname' for="aname">Assignment Name</label>
                                                        {{ form.aname }}
                                                        {{ form.errors.aname }}
                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label name='asubject' for="asubject">Subject Name</label>
                                                        {{ form.asubject }}
                                                        {{ form.errors.asubject }}
                                                    </div>
                                                    <div class="form-group mb-3">
                                                    <label for="adeadline">Deadline</label>
                                                        <input id="adeadline"  class="form-control"
                                                               name="adeadline" placeholder="Enter  Display">
                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label name='document' for="document">Document</label>
                                                        {{form.document}}
                                                        {{ form.errors.document }}
                                                    </div>
                                                    <div class="text-right">
                                                        <button type="submit" class="btn btn-success waves-effect waves-light">Create Note</button>
                                                    </div>
                                                </form>

                                    </div> <!-- end card-body-->
                                </div> <!-- end card-->
                            </div>
                            <!-- end col -->
                            
                        </div>
                        <!-- end row -->
                    </div> <!-- container -->

    <script>
        $('#adeadline').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: "yy-m-d"
        });
</script> 

{% endblock %}
{% block extra_javascript %}
{% endblock %}

templates/assignment/assignment-delete.html
{% extends "teacher_auth_base.html" %}
{% load static  %}
{% block extra_css %}
{% endblock %}

{% block content %}
    <!-- Start Content-->
    <!-- Start Content-->
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">

                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end page title -->

                        <div class="row">
                            <div class="col-10">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="header-title"></h4>
                                        <p class="sub-header">
                                        </p>

                                        <div class="row">
                                            <div class="col-lg-8">
                                                <form  action=" " method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div>
                                                        <h4 class="page-title" style="color:#006DF0 !important;">Delete Assignment?</h4>
                                                     </div>
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="text-right">
                                                                <button type="submit" class="btn btn-danger waves-effect waves-light">Delete</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div> <!-- end col -->
                                        </div>
                                        <!-- end row-->

                                    </div> <!-- end card-body -->
                                </div> <!-- end card -->
                            </div><!-- end col -->
                        </div>
                        <!-- end row -->
                    </div> <!-- container -->
{% endblock %}
{% block extra_javascript %}
{% endblock %}

templates/assignment/assignment-list.html
{% extends "teacher_auth_base.html" %}
{% load static  %}

{% block extra_css %}
{% endblock %}

{% block content %}

<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row" style="margin-top:-25px">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">CMS</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Assignment</a></li>
                        <li class="breadcrumb-item active">Assignment List</li>
                    </ol>
                </div>
                <h4 class="page-title">Assignment</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title"></h4>
                <p class="sub-header">

                </p>

                <div class="mb-2">
                    <div class="row">
                        <div class="col-12 text-sm-center form-inline">
<!--                                                <div class="form-group mr-2">-->
<!--                                                    <button id="demo-btn-addrow" class="btn btn-primary"><i class="mdi mdi-plus-circle mr-2"></i> Add Project</button>-->
<!--                                                </div>-->
                            <div class="form-group mr-2">
                                <a href="{% url 'assignment:assignment-create' %}" class="btn btn-primary" data-animation="fadein"  data-overlayColor="#98a6ad"><i class="mdi mdi-plus-circle mr-1"></i> Add Assignment</a>
                            </div>
                            <div class="form-group">
                                <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>

                <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
                    <thead>
                    <tr>
                        <th>Assignment Name</th>
                        <th>Faculty</th>
                        <th>Batch</th>
                        <th>Subject Name</th>
                        <th>Deadline</th>
                        <th>Document</th>
                        <th style="width: 85px;">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for assignment in assignments %}
                    <tr>
                    
                        <td>
                            {{assignment.aname}}
                        </td>
                        <td>
                            {{assignment.afname}}
                        </td>
                        <td>
                            {{assignment.asbatch}}
                        </td>
                        <td>
                            {{assignment.asubject}}
                        </td>
                        <td>
                            {{assignment.adeadline}}
                        </td>
                        <td>
                            <a href="{{assignment.document.url}}" class="btn btn-primary waves-effect waves-light">Download</a>
                            
                            </td>
                        
                        <td>
                            
                            <a href="{% url 'assignment:assignment-update' assignment.id %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                            <a href="{% url 'assignment:assignment-delete' assignment.id %}" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr class="active">
                        <td colspan="8">
                            <div class="text-right">
                                <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                            </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>
    <!-- end row -->


</div> <!-- container -->


{% endblock %}

{% block extra_javascript %}
{% endblock %}

templates/assignment/student-assignment-list.html
{% extends "student_auth_base.html" %}
{% load static  %}

{% block extra_css %}
{% endblock %}

{% block content %}

<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row" style="margin-top:-25px">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">CMS</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Assignment</a></li>
                        <li class="breadcrumb-item active">Assignment List</li>
                    </ol>
                </div>
                <h4 class="page-title">Assignment</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title"></h4>
                <p class="sub-header">

                </p>

                <div class="mb-2">
                    <div class="row">
                        <div class="col-12 text-sm-center form-inline">
<!--                                                <div class="form-group mr-2">-->
<!--                                                    <button id="demo-btn-addrow" class="btn btn-primary"><i class="mdi mdi-plus-circle mr-2"></i> Add Project</button>-->
<!--                                                </div>-->
                            <!-- <div class="form-group mr-2">
                                <a href="{% url 'assignment:assignment-create' %}" class="btn btn-primary" data-animation="fadein"  data-overlayColor="#98a6ad"><i class="mdi mdi-plus-circle mr-1"></i> Add Assignment</a>
                            </div> -->
                            <div class="form-group">
                                <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>

                <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
                    <thead>
                    <tr>
                        <th>Assignment Name</th>
                        <th>Faculty</th>
                        <th>Batch</th>
                        <th>Subject Name</th>
                        <th>Deadline</th>
                        <th>Document</th>
                        <!-- <th style="width: 85px;">Action</th> -->
                    </tr>
                    </thead>
                    <tbody>
                    {% for assignment in assignments %}
                    <tr>
                    
                        <td>
                            {{assignment.aname}}
                        </td>
                        <td>
                            {{assignment.afname}}
                        </td>
                        <td>
                            {{assignment.asbatch}}
                        </td>
                        <td>
                            {{assignment.asubject}}
                        </td>
                        <td>
                            {{assignment.adeadline}}
                        </td>
                        <td>
                            <a href="{{assignment.document.url}}" class="btn btn-primary waves-effect waves-light">Download</a>
                            
                            </td>
                        
                        <!-- <td>
                            
                            <a href="{% url 'assignment:assignment-update' assignment.id %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                            <a href="{% url 'assignment:assignment-delete' assignment.id %}" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                        </td> -->
                    </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr class="active">
                        <td colspan="8">
                            <div class="text-right">
                                <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                            </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>
    <!-- end row -->


</div> <!-- container -->


{% endblock %}

{% block extra_javascript %}
{% endblock %}