SchoolMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('teacher.urls')),
    path('',include('student.urls')),
    path('',include('faculty.urls')),
    path('',include('session.urls')),
    path('',include('attendance.urls')),
    path('',include('marks.urls')),
    path('',include('notice.urls')),
    path('',include('notes.urls')),
    path('',include('routine.urls')),
    path('',include('assignment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marks/urls.py
from django.urls import path
from .views import (
    MarksInp,
    ProvideMarks,
    Add_Marks,
    ShowMarks,
    MarksUpdate,
    get_package_detail,
    get_marks,
    deletemarks,
    MarksCreate,
    MarksOfStudent,
	)

app_name='marks'
urlpatterns = [
    path('marks-input/',MarksInp.as_view(),name='marks-input'),
    path('provide-marks/',ProvideMarks.as_view(),name='provide-marks'),
    path('add-marks',Add_Marks.as_view(),name='add-marks'),
    path('show-marks',ShowMarks.as_view(),name='show-marks'),
    path('marks-update/<int:pk>/',MarksUpdate.as_view(),name='marks-update'),
    path('marks-create/',MarksCreate.as_view(),name='marks-create'),
    path('delete-marks/<int:id>/',deletemarks,name='delete-marks'),
    path('marks-student/',MarksOfStudent.as_view(),name='marks-student'),

    path('package-detail/', get_package_detail, name='package-request'),
    path('get-marks/',get_marks,name='marks-request'),
    

]

marks/models.py
from django.db import models

from student.models import Student

class Marks(models.Model):
    sname = models.CharField(max_length=30)
    msemester = models.CharField(max_length=50)
    mexam = models.CharField(max_length=50)
    msubject = models.CharField(max_length=50)
    mmarks = models.IntegerField()
    mbatch = models.IntegerField(default=2072)
    fname = models.CharField(max_length=50,default='BSCCSIT')
    student = models.ForeignKey(Student,on_delete = models.SET_NULL,null = True,blank = True,related_name = 'student_marks')

    class Meta:
        db_table = "marks"

    def __str__(self):
        return self.msemester

marks/forms.py
from django import forms
from marks.models import Marks


class MarksForm(forms.ModelForm):
	sname = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Name Of Student'}
		), required=True, max_length=100)
	msemester = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Contact Person Name'}
		), required=False, max_length=50)
	mexam = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter  location'}
		), required=False, max_length=50)
	msubject = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter  location'}
		), required=False, max_length=50)
	mmarks = forms.IntegerField(widget=forms.NumberInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Contact Number'}
		), required=False)
	class Meta:
		model = Marks
		fields = ['sname','msemester','mexam','msubject','mmarks']

class MarksCreateForm(forms.ModelForm):
	sname = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Name Of Student'}
		), required=True, max_length=100)
	msemester = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Contact Person Name'}
		), required=False, max_length=50)
	mexam = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter  location'}
		), required=False, max_length=50)
	msubject = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter  location'}
		), required=False, max_length=50)
	mmarks = forms.IntegerField(widget=forms.NumberInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Contact Number'}
		), required=False)
	mbatch = forms.IntegerField(widget=forms.NumberInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter Contact Number'}
		), required=False)
	fname = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Enter  location'}
		), required=False, max_length=50)
	class Meta:
		model = Marks
		fields = ['sname','msemester','mexam','msubject','mmarks','mbatch','fname']

marks/views.py
from django.shortcuts import render,redirect,reverse
from django.views.generic import TemplateView
from django.contrib import messages
from django.http import HttpResponse
from django.http import HttpResponseRedirect,JsonResponse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
import sys,json

from faculty.models import Faculty
from student.models import Student
from .models import Marks
from .forms import MarksForm,MarksCreateForm


class MarksInp(TemplateView):
    def get (self,request):
        faculty=Faculty.objects.all()
        print('faculty',faculty)
        context = {
        'faculty':faculty,
        }
        return render(request, 'marks/marks-input.html',context)

class ProvideMarks(TemplateView):
	def post(self,request):
		afname = request.POST.get('faculty')
		asbatch = request.POST.get('batch')
		semester = request.POST.get('semester')
		exam = request.POST.get('exam')
		subject = request.POST.get('subject')
		faculty = Faculty.objects.get(fname=afname)
		faculty_id = faculty.id
		student = Student.objects.filter(sfaculty_id = faculty_id , sbatch = asbatch)
		context = {
		'faculty':afname,
		'batch' : asbatch,
		'semester' : semester,
		'exam' : exam,
		'subject' : subject,
		'students' : student,
		}
		marks = Marks.objects.filter(fname=afname,msubject=subject,msemester=semester,mbatch=asbatch,mexam=exam)
		if marks:
			messages.success(request,'Marks already uploaded')
			return render(request,"marks/marks-input.html",{})
		else:
			return render(request, "marks/provide-marks.html", context)


class Add_Marks(TemplateView):
	def post(self,request):
		mid=[]
		mexam = []
		mname = []
		msub=[]
		mmarks = []
		msem = []
		mbat = []
		mfna = []

		if request.method == "POST":
			count = int(request.POST.get('count'))
			print('count',count)
			for i in range(1, count+1):
				mid.append(request.POST.get('id{}'.format(i)))
				mexam.append(request.POST.get('exam{}'.format(i)))
				mname.append(request.POST.get('name{}'.format(i)))
				msub.append(request.POST.get('sub{}'.format(i)))
				mmarks.append(request.POST.get('marks{}'.format(i)))
				msem.append(request.POST.get('sem{}'.format(i)))
				mbat.append(request.POST.get('bat{}'.format(i)))
				mfna.append(request.POST.get('fna{}'.format(i)))
				id=mid[i-1]
				exam=mexam[i-1]
				name=mname[i-1]
				sub=msub[i-1]
				marks = mmarks[i-1]
				semester=msem[i-1]
				batch=mbat[i-1]
				fac=mfna[i-1]
				mar=Marks(msemester=semester,mexam=exam,msubject=sub,mmarks=marks,fname=fac,mbatch=batch,sname=name)
				mar.save()
			messages.success(request,'Marks successfully uploaded')
			# return redirect("../../marks")
			return HttpResponseRedirect('/marks-input')
		return HttpResponse('else')


# ajax

def get_marks(request):
    data = {'success': False} 
    if request.method=='POST':
        marks = request.POST.get('userbooks')
        mark = json.dumps(marks)
        print('marks',marks)
        print('mark',mark)
        data['success'] = True
        context = {
        'hey_marks' :marks,
        'hey_mark' : mark,
        }

    return render(request,"marks/show-marks.html",context)
# ajax

def get_package_detail(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        data1 = data['array']
        # data4 = data.dumps(data)
        print('data1',data1)
        context = {
        'data1': data1,
        # 'data4':data4,
        }
        return JsonResponse(context)
    else:
    	return render(request,"marks/show-marks.html",{})



class ShowMarks(TemplateView):
    def get(self,request):
        marks = Marks.objects.all()
        print('marks',marks)
        for mark in marks:
            print(mark.sname)
        return redirect(reverse('marks:marks-input'))
    def post(self,request):
        fname = request.POST.get('faculty')
        mbatch = request.POST.get('batch')
        msemester = request.POST.get('semester')
        marks = Marks.objects.filter(msemester=msemester,mbatch=mbatch,fname=fname)
        return render(request,"marks/show-marks.html",{'marks' : marks })



class MarksUpdate(UpdateView):
    model = Marks
    template_name = 'marks/marks-update.html'
    form_class = MarksForm
    success_url = '/show-marks'

def deletemarks(request, id):
    marks = Marks.objects.get(id=id)
    marks.delete()
    return redirect(reverse('marks:marks-input'))

class MarksCreate(CreateView):
    model=Marks
    template_name = 'marks/marks-create.html'
    form_class = MarksCreateForm
    success_url = '/marks-input/'


class MarksOfStudent(TemplateView):
    def get(self,request):
        faculty=request.session['user_faculty']
        batch=request.session['user_batch']
        sid=request.session['user_id']
        sname=request.session['user_name']
        totalt=0
        totalm=0
        totalp=0
        scount_test=0
        scount_mid=0
        scount_pre=0
        flag1='Pass'
        flag2='Pass'
        flag3='Pass'
        p=[]
        marks = Marks.objects.filter(sname=sname,mbatch=batch,fname=faculty)
        print('marks',marks)
        marks_test = Marks.objects.filter(sname=sname,mbatch=batch,fname=faculty,mexam='Class Test')
        print('class test',marks_test)
        marks_mid = Marks.objects.filter(sname=sname,mbatch=batch,fname=faculty,mexam='Mid-Term')
        marks_pre = Marks.objects.filter(sname=sname,mbatch=batch,fname=faculty,mexam='Pre-Board')

        for mt in marks_test:
            totalt=totalt+mt.mmarks
            if (mt.msubject):
                scount_test=scount_test+1
            if(mt.mmarks<24):
                flag1='Fail'
        
        for mm in marks_mid:
            totalm = totalm + mm.mmarks
            if (mt.msubject):
                scount_mid=scount_mid+1
            if(mm.mmarks<24):
                flag2='Fail'

        for mp in marks_pre:
            totalp = totalp + mp.mmarks
            if (mt.msubject):
                scount_pre=scount_pre+1
            if(mp.mmarks<24):
                flag3='Fail'

        percent={}
        if scount_test!=0:
            percent['test_percent']=(totalt/scount_test)
        if scount_mid!=0:
            percent['mid_percent']=(totalm/scount_mid)
            print('percent',percent['mid_percent'])
        if scount_pre!=0:
            percent['pre_percent']=(totalp/scount_pre)
        percent['test_pass']=flag1
        percent['mid_pass'] = flag2
        percent['pre_pass'] = flag3
        

        # m1={'marks':marks}
        # m2={'marks_mid':marks_mid}
        # m3={'marks_pre':marks_pre}
        # m= {**m1,**m2,**m3,**percent}

        context = {
        'marks_test':marks_test,
        'marks_mid':marks_mid,
        'marks_pre':marks_pre,
        **percent,

        }
        return render(request,"marks/marks-student.html",context)

templates/marks/marks-create.html
    


{% extends "teacher_auth_base.html" %}
{% load static  %}
{% block extra_css %}
{% endblock %}
{% block content %}
    <!-- Start Content-->
    <!-- Start Content-->
                    <div class="container-fluid">
                        <!-- start page title -->
                            <div class="row" style="margin-top:-25px">
                                <div class="col-12">
                                    <div class="page-title-box">
                                        <div class="page-title-right">
                                            <ol class="breadcrumb m-0">
                                                <li class="breadcrumb-item"><a href="javascript: void(0);">Marks Info</a></li>
                                                <li class="breadcrumb-item"><a href="javascript: void(0);">Marks</a></li>
                                                <li class="breadcrumb-item active">Update Marks</li>
                                            </ol>
                                        </div>
                                        <h4 class="page-title"></h4>
                                    </div>
                                </div>
                            </div>
                            <!-- end page title -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="mb-3 header-title">Update Marks</h4>
                                        <form  action=" " method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="form-group mb-3">
                                                        <label for="Username">Student Name</label>
                                                        {{form.sname}}

                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label for="Semester">Semester</label>
                                                        {{form.msemester}}

                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label for="Type of Exam">Type of Exam</label>
                                                        {{form.mexam}}

                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label for="Subject">Subject</label>
                                                        {{form.msubject}}

                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label for="anniversary">Marks</label>
                                                        {{ form.mmarks }}
                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label for="anniversary">Batch</label>
                                                        {{ form.mbatch }}
                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label for="anniversary">fname</label>
                                                        {{ form.fname }}
                                                    </div>
                                                    <div class="text-right">
                                                        <button type="submit" class="btn btn-success waves-effect waves-light">Update Marks</button>
                                                    </div>
                                                </form>

                                    </div> <!-- end card-body-->
                                </div> <!-- end card-->
                            </div>
                            <!-- end col -->
                            
                        </div>
                        <!-- end row -->
                    </div> <!-- container -->

{% endblock %}
{% block extra_javascript %}
{% endblock %}

templates/marks/marks-input.html
{% extends "teacher_auth_base.html" %}
{% load static  %}

{% block extra_css %}
{% endblock %}

{% block content %}


{% if messages %}
  <!-- <ul class="messages"> -->
    {% for message in messages %}
      <!-- <li class="{{ message.tags }}">{{ message }}</li> -->
      <script>alert('{{message}}')</script>
    {% endfor %}
{% endif %}

<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row" style="margin-top:-25px">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Teacher Info</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Teacher</a></li>
                        <li class="breadcrumb-item active">School Management System</li>
                    </ol>
                </div>
                <h4 class="page-title">Teacher</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h4 class="mb-3 header-title">View Marks</h4>

                <form action="{% url 'marks:show-marks'  %}" method="post"  enctype="multipart/form-data">
                        {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Faculty</label>
                        <!-- <select class="form-control" name="faculty" id="exampleInputEmail1">
                              <option value="{{faculty.fid}}">{{faculty}}</option>
                        </select> -->
                        <select name="faculty" id="exampleInputEmail1" required="True"
                                class="form-control">
                            <!-- <option selected disabled>Select Your Faculty</option> -->
                            {% for fac in faculty %}
                                <option>{{ fac }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        
                        <label for="exampleInputPassword1">Batch</label>
                        <select class="form-control" name="batch"  placeholder="Select batch" id="exampleInputPassword1">
                          <option value="2068">2068</option>
                          <option value="2069">2069</option>
                          <option value="2070">2070</option>
                          <option value="2071">2071</option>
                          <option value="2072">2072</option>
                          <option value="2073">2073</option>
                          <option value="2074">2074</option>
                        </select>
                    </div>
                    <div class="form-group">
                      <label for="exampleInputPassword2">Semester</label>
                      <select class="form-control" name="semester" placeholder="Select batch" id="exampleInputPassword2">
                        <option value="First">First</option>
                        <option value="Second">Second</option>
                        <option value="Third">Third</option>
                        <option value="Fouth">Fourth</option>
                        <option value="Fifth">Fifth</option>
                        <option value="Sixth">Sixth</option>
                        <option value="Seventh">Seventh</option>
                        <option value="Eighth">Eighth</option>
                      </select>
                    </div>
                    <div class="form-group row mb-3 justify-content-end">
                        
                    </div>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">View Marks</button>
                </form>

            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div>
    <!-- end col -->

    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">

                <h4 class="mb-3 header-title">Update Marks</h4>

                
                <form action="{% url 'marks:provide-marks' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Faculty</label>
                        <!-- <select class="form-control" name="faculty" id="exampleInputEmail1">
                              <option value="{{faculty.fid}}">{{faculty}}</option>
                        </select> -->
                        <select name="faculty" id="exampleInputEmail1" required="True"
                                class="form-control">
                            <!-- <option selected disabled>Select Your Faculty</option> -->
                            {% for fac in faculty %}
                                <option>{{ fac }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        
                        <label for="exampleInputPassword1">Batch</label>
                        <select class="form-control" name="batch"  placeholder="Select batch" id="exampleInputPassword1">
                          <option value="2068">2068</option>
                          <option value="2069">2069</option>
                          <option value="2070">2070</option>
                          <option value="2071">2071</option>
                          <option value="2072">2072</option>
                          <option value="2073">2073</option>
                          <option value="2074">2074</option>
                        </select>
                    </div>
                    <div class="form-group">
                        
                        <label for="exampleFormControlSelect2">Semester</label>
                        <select class="form-control" name="semester" placeholder="Select semester" id="exampleFormControlSelect2">
                          <option value="First">First</option>
                          <option value="Second">Second</option>
                          <option value="Third">Third</option>
                          <option value="Fourth">Fourth</option>
                          <option value="Fifth">Fifth</option>
                          <option value="Sixth">Sixth</option>
                          <option value="Seventh">Seventh</option>
                        </select>
                    </div>
                    <div class="form-group">
                      <label for="exampleFormControlSelect2">Exam type</label>
                      <select class="form-control" placeholder="Select batch" name="exam" id="exampleFormControlSelect2">
                         <option value="Class Test">Class Test</option>
                        <option value="Mid-Term">Mid-Term</option>
                        <option value="Pre-Board">Pre-Board</option>
                        <option value="Final">Final</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="exampleFormControlSelect2">Subject</label>
                      <input type="text" name="subject" class="form-control">
                    </div>
                    <div class="form-group row mb-3 justify-content-end">
                        
                    </div>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Update Marks</button>
                </form>
            </div>  <!-- end card-body -->
        </div>  <!-- end card -->
    </div>  <!-- end col -->

</div>
<!-- end row -->


</div> <!-- container -->

<script>
  $("#form_id").on('submit', function(event) {
       event.preventDefault(); 
       var userbooks = '{{ userbooks }}';
       $.ajax({
           type: "POST",
           url: "{% url 'marks:marks-request' %}",
           data:{
                 userbooks:userbooks, 
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
           },
           datatype:'json',
           success: function(data) {
             if (data['success'])
                alert("successfully added to favorites")
           }
       }); 
  });
</script>


{% endblock %}

{% block extra_javascript %}
{% endblock %}

templates/marks/show-marks.html
{% extends "teacher_auth_base.html" %}
{% load static  %}

{% block extra_css %}
{% endblock %}

{% block content %}




<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row" style="margin-top:-25px">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Student Marks Info</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Student</a></li>
                        <li class="breadcrumb-item active">Marks</li>
                    </ol>
                </div>
                <h4 class="page-title">Marks</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title"></h4>
                <p class="sub-header">

                </p>

                <div class="mb-2">
                    <div class="row">
                        <div class="col-12 text-sm-center form-inline">
<!--                                                <div class="form-group mr-2">-->
<!--                                                    <button id="demo-btn-addrow" class="btn btn-primary"><i class="mdi mdi-plus-circle mr-2"></i> Add Project</button>-->
<!--                                                </div>-->
                            <div class="form-group mr-2">
                                <a href="{% url 'marks:marks-create' %}" class="btn btn-primary" data-animation="fadein"  data-overlayColor="#98a6ad" id="id_package" ><i class="mdi mdi-plus-circle mr-1"></i> Add Marks</a>
                            </div>
                            <div class="form-group">
                                <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>

                <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
                    <thead>
                    <tr>
                        <th>Student Name</th>
                        <th>Semester</th>
                        <th>Types of Exam</th>
                        <th>Subjects</th>
                        <th>Marks</th>
                        <th style="width: 85px;">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if marks %}
                    {% for mark in marks %}
                    <tr>
                        <td>{{ mark.sname }}</td>
                        <td>{{ mark.msemester }}</td>
                        <td>{{ mark.mexam }}</td>
                        <td>{{ mark.msubject }}</td>
                        <td>{{ mark.mmarks }}</td>
                        <td>
                            <a href="{% url 'marks:marks-update' mark.id %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                            <a href="{% url 'marks:delete-marks' mark.id %}" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% elif data %}
                    {% for mark in data1 %}
                    <tr>
                        <td>{{ mark.sname }}</td>
                        <td>{{ mark.msemester }}</td>
                        <td>{{ mark.mexam }}</td>
                        <td>{{ mark.msubject }}</td>
                        <td>{{ mark.mmarks }}</td>
                        <td>
                            <a href="{% url 'marks:marks-update' mark.id %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                            <a href="#" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                    </tbody>
                    <tfoot>
                    <tr class="active">
                        <td colspan="8">
                            <div class="text-right">
                                <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                            </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>

    
                            
    <!-- end row -->

</div> <!-- container -->




<script>
            // var marks = '{{marks}}';
            // $.ajax({
            //     type: "GET",
            //     url: '{% url 'marks:package-request' %}',
            //     data: {'array': marks},
            //     success: function(result) {
            //         console.log(result.d);
            //     },
            //     error:function (result) {
            //         console.log(result);
            //     }
            // });

                   var userbooks = '{{ marks }}';
                   $.ajax({
                       type: "POST",
                       url: "{% url 'marks:marks-request' %}",
                       data:{
                             userbooks:userbooks, 
                       },
                       headers: {"X-CSRFToken":'{{ csrf_token }}'},
                       datatype:'json',
                       success: function(data) {
                         if (data['success'])
                            alert("successfully added to favorites")
                       },
                    //    success: function (data) {

                    //     document.getElementById('cake-package').text = data;

                    //     document.getElementById('cake-flavour').text = json['flavour'];
                    //     document.getElementById('cake-quantity').text = json['quantity'];

                    // },
                   }); 
                
                // const timeSeries = `{{ marks | safe }}`;
                // console.log(timeSeries);


    
        // var marks = `{{marks}}`;
        // $.ajax({
        //     url: '{% url 'marks:package-request' %}',
        //     type: 'POST',
        //     data: JSON.stringify({'array': marks}),
        //     processData: false,
        //     contentType: "application/json",
        //     dataType: "json",
        //     headers: {"X-CSRFToken":'{{ csrf_token }}'},
        //     success: function (result) {
        //         console.log(result.d);
        //     },

        //     success: function (json) {

        //         document.getElementById('cake-package').text = json['data1'];
        //     },

        //     error: function (result) {
        //         console.log(result);
        //     }
        //   });


</script>

{% endblock %}

{% block extra_javascript %}
{% endblock %}