SchoolMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('teacher.urls')),
    path('',include('student.urls')),
    path('',include('faculty.urls')),
    path('',include('session.urls')),
    path('',include('attendance.urls')),
    path('',include('marks.urls')),
    path('',include('notice.urls')),
    path('',include('notes.urls')),
    path('',include('routine.urls')),
    path('',include('assignment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/urls.py
from django.urls import path
from .views import (
    Attendance,
    TakeAttendance,
    # update_attendance,
    Update_Attendance,
    ViewAttendance,
    StdAttendance,
	)

app_name='attendance'
urlpatterns = [
    path('attendance/',Attendance.as_view(),name='attendance'),
    path('take-attendance/',TakeAttendance.as_view(),name='take-attendance'),
    path('Update-Attendance/<str:faculty>/<int:batch>/',Update_Attendance.as_view(),name='update-attendance'),
    path('view-attendance',ViewAttendance.as_view(),name='view-attendance'),
    path('student-attendance',StdAttendance,name='student-attendance'),
]

marks/urls.py
from django.urls import path
from .views import (
    MarksInp,
    ProvideMarks,
    Add_Marks,
    ShowMarks,
    MarksUpdate,
    get_package_detail,
    get_marks,
    deletemarks,
    MarksCreate,
    MarksOfStudent,
	)

app_name='marks'
urlpatterns = [
    path('marks-input/',MarksInp.as_view(),name='marks-input'),
    path('provide-marks/',ProvideMarks.as_view(),name='provide-marks'),
    path('add-marks',Add_Marks.as_view(),name='add-marks'),
    path('show-marks',ShowMarks.as_view(),name='show-marks'),
    path('marks-update/<int:pk>/',MarksUpdate.as_view(),name='marks-update'),
    path('marks-create/',MarksCreate.as_view(),name='marks-create'),
    path('delete-marks/<int:id>/',deletemarks,name='delete-marks'),
    path('marks-student/',MarksOfStudent.as_view(),name='marks-student'),

    path('package-detail/', get_package_detail, name='package-request'),
    path('get-marks/',get_marks,name='marks-request'),
    

]

attendance/models.py
from django.db import models

from student.models import Student

class Daily(models.Model):
	std_id = models.IntegerField(null=True,blank=True)
	std_name = models.CharField(max_length=100)
	date= models.DateField()
	attendance = models.BooleanField(default=False)
	faculty = models.CharField(max_length=20)
	batch = models.IntegerField()

	def __str__(self):
		return (self.std_name + " - Batch : " + str(self.batch))

class Semester(models.Model):
	# std_id = models.IntegerField()
	# roll_no= models.IntegerField()
	std_name = models.CharField(max_length=100)
	semester =  models.CharField(max_length=10)
	present_days = models.IntegerField(default=30)
	absent_days = models.IntegerField()
	working_days = models.IntegerField()
	faculty = models.CharField(max_length=20)
	batch = models.IntegerField()

class Meta:
		db_table = "semester"

attendance/forms.py
from django import forms
from .models import Daily

class DailyForm(forms.ModelForm):
    # std_name = forms.CharField(widget=forms.TextInput(
    #     attrs={'class': 'form-control', 'placeholder': 'Enter Name of Student'}
    # ), required=True, max_length=100)
    # date = forms.DateField(widget=forms.DateInput(
    #     attrs={'class': 'form-control', 'placeholder': 'Enter date ', 'id': 'Anniversary'}
    # ), required=False)
    # location = forms.CharField(widget=forms.TextInput(
    #     attrs={'class': 'form-control', 'placeholder': 'Enter  location'}
    # ), required=False, max_length=50)
    faculty = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Faculty of Student'}
    ), required=True, max_length=100)
    batch = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter batch'}
    ), required=False)


    class Meta:
        model = Organization
        fields = ['faculty', 'batch']

attendance/views.py
from django.shortcuts import render,redirect,reverse
from django.views.generic import TemplateView
import datetime
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from faculty.models import Faculty
from student.models import Student
from .models import Daily
from .models import Semester

from django.db.models import Count



class Attendance(TemplateView):
    def get (self,request):
        faculty=Faculty.objects.all()
        print('faculty',faculty)
        context = {
        'faculty':faculty,
        }
        return render(request, 'attendance/attendance.html',context)

class TakeAttendance(TemplateView):
	def get(self,request):
		return redirect(reverse('attendance:attendance'))
	def post(self,request):
		faculty = request.POST.get('faculty')
		print('faculty',faculty)
		batch = request.POST.get('batch')
		fac = Faculty.objects.get(fname=faculty)
		student = Student.objects.filter(sfaculty=fac.id,sbatch=batch)
		print('student',student)
		context = {
		'students':student,
		'faculty':fac,
		'batch' : batch,
		}
		return render(request,"attendance/take-attendance.html",context)


class Update_Attendance(TemplateView):
	def post(self, request, *args, **kwargs,):
		values = []
		names = []
		atts = []
		x = datetime.datetime.now()
		if request.method == "POST":
			count = int(request.POST.get('count'))
			
			for i in range(1, count+1):
				values.append(request.POST.get('id{}'.format(i)))
				print('values-format',values)
				names.append(request.POST.get('name{}'.format(i)))
				print('name-format',names)
				atts.append(request.POST.get('att{}'.format(i)))
				print('atten',atts)
				id=values[i-1]
				name=names[i-1]
				atte = atts[i-1]
				print('id-',id)
				print('name-',name)
				print('atten-',atte)
				print('faculty',self.kwargs['faculty'])
				print('batch',self.kwargs['batch'])
				att=Daily(std_id=id,std_name=name,date=x.strftime("%Y-%m-%d"),attendance=atte,faculty=self.kwargs['faculty'],batch=self.kwargs['batch'])
				att.save()
			
			messages.success(request,'Attendance successfully updated')
			return HttpResponseRedirect('/attendance')


class ViewAttendance(TemplateView):
	def get(self,request):
		return redirect(reverse('attendance:attendance'))
	def post(self,request):
		faculty = request.POST.get('faculty')
		batch = request.POST.get('batch')
		sem = request.POST.get('semester')
		distinct = Daily.objects.values('std_name').annotate(name_count=Count('std_name'))
		# print('-----------',distinct)
		att1 = ([item['std_name'] for item in distinct])
		# print('attribute',att1)
		# att = Daily.objects.filter(faculty=faculty, batch=batch,std_name__in=[item['std_name'] for item in distinct])
		
		for attribute in att1:
			attendances=Daily.objects.filter(faculty=faculty, batch=batch,std_name=attribute)
			present_days=0
			absent_days=0
			working_days=0
			# print('attendances',attendances)
			for attendance_attribute in attendances:
				if attendance_attribute.attendance == True:
					present_days=present_days+1
				elif attendance_attribute.attendance==False:
					absent_days = absent_days+1
				working_days = present_days+absent_days
			calls=Semester.objects.all()
			# print('calls------------',calls)
			semester=Semester(std_name=attendance_attribute.std_name,semester=sem,present_days=present_days,absent_days=absent_days,working_days=working_days,faculty=faculty,batch=batch)
			print('sem',semester.std_name)
			print('sem-id',semester.id)
			distinct1 = Semester.objects.values('std_name').annotate(name_count=Count('std_name'))
			att2 = ([item1['std_name'] for item1 in distinct1])
			if calls:
				print('insideif------------------')
				for call in att2:
					if semester.std_name in att2:
						print('update')
						p=Semester.objects.get(std_name=semester.std_name)
						print('p',p)
						c=Semester.objects.filter(id=p.id).update(std_name=attendance_attribute.std_name,semester=sem,present_days=present_days,absent_days=absent_days,working_days=working_days,faculty=faculty,batch=batch)
						print('update-working-days',c)
					else:
						semester.save()
			else:
				semester.save()
		# for attendances in att:
		# 	if attendances.attendance==True:
		# 		present_days=present_days+1
		# 	elif attendances.attendance==False:
		# 		absent_days = absent_days+1
			# print('present_days',present_days)
			# print('absent_days',absent_days)
			# print('working_days',working_days)
		student = Semester.objects.filter(semester=sem,batch=batch,faculty=faculty)
		context = {
		'students':student,

		}
		return render(request,"attendance/view-attendance.html",context)


# class StdAttendance(TemplateView):
# 	def get(self,request):
# 		return render(request,"attendance/piechart.html",{})
# 	def post(self,request):
# 		name = request.session['user_name']
# 		print('name',name)
# 		if request.method == "POST":
# 			sem=request.POST.get('sem')
# 			attendance=Semester.objects.get(std_name=name,semester=sem)
# 			context = {
# 			'sem':sem,
# 			'attendance':attendance,
# 			}
# 			return render(request,"attendance/piechart.html",context)
# 		else:
# 			sem='First'
# 			attendance= Semester.objects.get(std_name=name,semester=sem)
# 			# attendance= semester.objects.filter(std_id=id)
# 			# return HttpResponse(attendance)
# 			context = {
# 			'sem':sem,
# 			'attendance':attendance,
# 			}
# 			return render(request,"attendance/piechart.html",context)


def StdAttendance(request):
	name = request.session['user_name']
	if request.method == "POST":
		sem=request.POST.get('sem')
		attendance=Semester.objects.get(std_name=name,semester=sem)
		context = {
		'sem':sem,
		'attendance':attendance,
		}
		return render(request,"attendance/piechart.html",context)
	else:
		sem='First'
		attendance= Semester.objects.get(std_name=name,semester=sem)
		# attendance= semester.objects.filter(std_id=id)
		# return HttpResponse(attendance)
		context = {
		'sem':sem,
		'attendance':attendance,
		}
		return render(request,"attendance/piechart.html",context)

templates/attendance/attendance.html
{% extends "teacher_auth_base.html" %}
{% load static  %}

{% block extra_css %}
{% endblock %}

{% block content %}

{% if messages %}
  <!-- <ul class="messages"> -->
    {% for message in messages %}
      <!-- <li class="{{ message.tags }}">{{ message }}</li> -->
      <script>alert('{{message}}')</script>
    {% endfor %}
{% endif %}

<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row" style="margin-top: -25px">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Teacher Info</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Teacher</a></li>
                        <li class="breadcrumb-item active">School Management System</li>
                    </ol>
                </div>
                <h4 class="page-title">Teacher</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h4 class="mb-3 header-title">Take Attendence</h4>

                <form action="{% url 'attendance:take-attendance'  %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Faculty</label>
                        <!-- <select class="form-control" name="faculty" id="exampleInputEmail1">
                              <option value="{{faculty.fid}}">{{faculty}}</option>
                        </select> -->
                        <select name="faculty" id="exampleInputEmail1" required="True"
                                class="form-control">
                            <!-- <option selected disabled>Select Your Faculty</option> -->
                            {% for fac in faculty %}
                                <option>{{ fac }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        
                        <label for="exampleInputPassword1">Batch</label>
                        <select class="form-control" name="batch"  placeholder="Select batch" id="exampleInputPassword1">
                          <option value="2068">2068</option>
                          <option value="2069">2069</option>
                          <option value="2070">2070</option>
                          <option value="2071">2071</option>
                          <option value="2072">2072</option>
                          <option value="2073">2073</option>
                          <option value="2074">2074</option>
                        </select>
                    </div>
                    <div class="form-group row mb-3 justify-content-end">
                        
                    </div>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Take Attendance</button>
                </form>

            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div>
    <!-- end col -->

    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">

                <h4 class="mb-3 header-title">View Attendance</h4>

                
                <form action="{% url 'attendance:view-attendance' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Faculty</label>
                        <!-- <select class="form-control" name="faculty" id="exampleInputEmail1">
                              <option value="{{faculty.fid}}">{{faculty}}</option>
                        </select> -->
                        <select name="faculty" id="exampleInputEmail1" required="True"
                                class="form-control">
                            <!-- <option selected disabled>Select Your Faculty</option> -->
                            {% for fac in faculty %}
                                <option>{{ fac }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        
                        <label for="exampleInputPassword1">Batch</label>
                        <select class="form-control" name="batch"  placeholder="Select batch" id="exampleInputPassword1">
                          <option value="2068">2068</option>
                          <option value="2069">2069</option>
                          <option value="2070">2070</option>
                          <option value="2071">2071</option>
                          <option value="2072">2072</option>
                          <option value="2073">2073</option>
                          <option value="2074">2074</option>
                        </select>
                    </div>
                    <div class="form-group">
                        
                        <label for="exampleFormControlSelect2">Semester</label>
                        <select class="form-control" name="semester" placeholder="Select semester" id="exampleFormControlSelect2">
                          <option value="First">First</option>
                          <option value="Second">Second</option>
                          <option value="Third">Third</option>
                          <option value="Fourth">Fourth</option>
                          <option value="Fifth">Fifth</option>
                          <option value="Sixth">Sixth</option>
                          <option value="Seventh">Seventh</option>
                        </select>
                    </div>
                    <div class="form-group row mb-3 justify-content-end">
                        
                    </div>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">View Attendance</button>
                </form>
            </div>  <!-- end card-body -->
        </div>  <!-- end card -->
    </div>  <!-- end col -->

</div>
<!-- end row -->


</div> <!-- container -->


{% endblock %}

{% block extra_javascript %}
{% endblock %}

templates/attendance/piechart.html
{% extends "student_auth_base.html" %}
{% load static  %}

{% block extra_css %}
{% endblock %}

{% block content %}

{% if messages %}
  <!-- <ul class="messages"> -->
    {% for message in messages %}
      <!-- <li class="{{ message.tags }}">{{ message }}</li> -->
      <script>alert('{{message}}')</script>
    {% endfor %}
{% endif %}

<!-- Start Content-->
<div class="container-fluid">

    
    <!-- end page title -->

<div class="row" style="margin-top: -25px">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">

                <form action="{% url 'attendance:student-attendance'  %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                         <div class="row">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                <div class="form-group">
                                <label for="exampleFormControlSelect2">Semester</label>
                                <select class="form-control" placeholder="Select batch" name="sem" id="exampleFormControlSelect2">
                                  <option value="{{sem}}">{{sem}}</option>
                                  <option value="First">First</option>
                                  <option value="Second">Second</option>
                                  <option value="Third">Third</option>
                                  <option value="Fourth">Fourth</option>
                                  <option value="Fifth">Fifth</option>
                                  <option value="Sixth">Sixth</option>
                                  <option value="Seventh">Seventh</option>
                                </select>
                              </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                <!-- <div class="form-group">
                                    <label for="date2">End Date </label>
                                    {{ form.date_end }}

                                </div> -->
                            </div>

                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                <div class="form-group">
                                    <button style="margin-top:25px;" type="submit"
                                            class="btn btn-primary waves-effect waves-light">
                                        View 
                                    </button>
                                </div>
                            </div>
                        </div>
                </form>

                
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div>
    <!-- end col -->


</div>
<!-- end row -->


</div> <!-- container -->


<div id="piechart"></div>

                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

                <script type="text/javascript">

                // Load google charts
                google.charts.load('current', {'packages':['corechart']});
                google.charts.setOnLoadCallback(drawChart);

                // Draw the chart and set the chart values

                function drawChart() {
                  var data = google.visualization.arrayToDataTable([
                  ['Task', 'Hours per Day'],
                  ['Present days',{{attendance.present_days}}],
                  ['Absent days', {{attendance.absent_days}}],
                ]);


                  // Optional; add a title and set the width and height of the chart
                  var options = {'title':'Attendance', 'width':550, 'height':400};

                  // Display the chart inside the <div> element with id="piechart"
                  var chart = new google.visualization.PieChart(document.getElementById('piechart'));
                  chart.draw(data, options);
                }

                </script>



{% endblock %}

{% block extra_javascript %}
{% endblock %}

templates/attendance/take-attendance.html
{% extends "teacher_auth_base.html" %}
{% load static  %}

{% block extra_css %}
{% endblock %}

{% block content %}

<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row" style="margin-top:-25px">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Teacher Info</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Teacher</a></li>
                        <li class="breadcrumb-item active">School Management System</li>
                    </ol>
                </div>
                <h4 class="page-title">Teacher</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

  



    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title"></h4>
                <p class="sub-header">

                </p>

                <div class="mb-2">
                    <div class="row">
                        <div class="col-12 text-sm-center form-inline">
<!--                                                <div class="form-group mr-2">-->
<!--                                                    <button id="demo-btn-addrow" class="btn btn-primary"><i class="mdi mdi-plus-circle mr-2"></i> Add Project</button>-->
<!--                                                </div>-->
                            <!-- <div class="form-group mr-2">
                                <a href="#" class="btn btn-primary" data-animation="fadein"  data-overlayColor="#98a6ad"><i class="mdi mdi-plus-circle mr-1"></i> Add Teacher</a>
                            </div> -->
                            <div class="form-group">
                                <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>

                <form method="POST" class="post-form" action="{% url 'attendance:update-attendance' faculty batch %}">
                    {% csrf_token %}

                <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
                    <thead>
                    <tr>
                        <th>ROLL NO</th>
                        <th>NAME</th>
                        <th>ATTENDANCE</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for student in students %}
                    <tr>
                         <td><input type="hidden" name="id{{forloop.counter}}" value="{{student.id}}">{{student.id}}</td>
                         <td><input type="hidden" name="name{{forloop.counter}}" value="{{student.sname}}">{{student.sname}}</td>
                         <td><input type="number" name="att{{forloop.counter}}" min="0" max="1" class="btn btn-primary waves-effect waves-light"></td>
                   </tr>
                   <input type="hidden" name="count" value="{{ forloop.counter }}">
                   {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr class="active">
                        <td colspan="8">
                            <div class="text-right">
                                <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                            </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>
                <label>
                   <button type="submit" class="btn btn-success" style="margin-top:30px;margin-left: 10px; ">Submit</button>
                 </label>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>
    <!-- end row -->


</div> <!-- container -->


{% endblock %}

{% block extra_javascript %}
{% endblock %}

templates/attendance/view-attendance.html
{% extends "teacher_auth_base.html" %}
{% load static  %}

{% block extra_css %}
{% endblock %}

{% block content %}



<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12" style="margin-top:-25px">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Student Marks Info</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Student</a></li>
                        <li class="breadcrumb-item active">Marks</li>
                    </ol>
                </div>
                <h4 class="page-title">Marks</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title"></h4>
                <p class="sub-header">

                </p>

                <div class="mb-2">
                    <div class="row">
                        <div class="col-12 text-sm-center form-inline">
<!--                                                <div class="form-group mr-2">-->
<!--                                                    <button id="demo-btn-addrow" class="btn btn-primary"><i class="mdi mdi-plus-circle mr-2"></i> Add Project</button>-->
<!--                                                </div>-->
                            <div class="form-group mr-2">
                                <a href="{% url 'marks:marks-create' %}" class="btn btn-primary" data-animation="fadein"  data-overlayColor="#98a6ad" id="id_package" ><i class="mdi mdi-plus-circle mr-1"></i> Add Marks</a>
                            </div>
                            <div class="form-group">
                                <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>

                <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
                    <thead>
                    <tr>
                        <th>ROLL NO</th>
                        <th>STUDENT NAME</th>
                        <th>SEMESTER</th>
                        <th>PRESENT DAYS</th>
                        <th>ABSENT DAYS</th>
                        <th>WORKING DAYS</th>
                        <th>FACULTY</th>
                        <th>BATCH</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for student in students %}
                    <tr>
                        <th>{{ student.id }}</th>
                        <td>{{ student.std_name }}</td>
                        <td>{{ student.semester }}</td>
                        <td>{{ student.present_days }}</td>
                        <td>{{ student.absent_days }}</td>
                        <td>{{ student.working_days }}</td>
                        <td>{{ student.faculty }}</td>
                        <td>{{ student.batch }}</td>
                   </tr>
                   {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr class="active">
                        <td colspan="8">
                            <div class="text-right">
                                <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                            </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>

    <!-- end row -->

</div> <!-- container -->

{% endblock %}

{% block extra_javascript %}
{% endblock %}